// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3v85qvYp0wWwf9QPpxASrCCrlUQ5vr-U',
    appId: '1:341755586868:web:ac9ce6e40dbed709e75d61',
    messagingSenderId: '341755586868',
    projectId: 'chat-app-6fdd6',
    authDomain: 'chat-app-6fdd6.firebaseapp.com',
    storageBucket: 'chat-app-6fdd6.appspot.com',
    measurementId: 'G-N9QYZE3DRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0WtLeB9dpGzwKW8q4JDFZn4YcLWaOf50',
    appId: '1:341755586868:android:d78371164f8067c4e75d61',
    messagingSenderId: '341755586868',
    projectId: 'chat-app-6fdd6',
    storageBucket: 'chat-app-6fdd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwxCOjyaeoBspxe4sTBPzhmaW4Sv0o97w',
    appId: '1:341755586868:ios:0f98e4d257a5acdbe75d61',
    messagingSenderId: '341755586868',
    projectId: 'chat-app-6fdd6',
    storageBucket: 'chat-app-6fdd6.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwxCOjyaeoBspxe4sTBPzhmaW4Sv0o97w',
    appId: '1:341755586868:ios:0f98e4d257a5acdbe75d61',
    messagingSenderId: '341755586868',
    projectId: 'chat-app-6fdd6',
    storageBucket: 'chat-app-6fdd6.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3v85qvYp0wWwf9QPpxASrCCrlUQ5vr-U',
    appId: '1:341755586868:web:840e2565a97894fbe75d61',
    messagingSenderId: '341755586868',
    projectId: 'chat-app-6fdd6',
    authDomain: 'chat-app-6fdd6.firebaseapp.com',
    storageBucket: 'chat-app-6fdd6.appspot.com',
    measurementId: 'G-7ME1WXB7GB',
  );
}
